[package]
name = "screenshot-backend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = { version = "0.5.0-rc.2", features = ["secrets", "tls", "json"] }
serde = { version = "1.0.144", features = ["derive"] }
serde_json = "1.0.85"
tera = "1.17.1"
lazy_static = "1.4.0"
uuid = { version = "1.1.2", features = ["v4", "fast-rng", "serde"] }
infer = "0.9.0"
magic = "0.13.0"
