[package]
name = "screenshot-backend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
figment = { version = "0.10", features = ["env", "toml"] }
rocket = { version = "0.5.0-rc.2", features = ["secrets", "tls", "json"] }
serde = { version = "1.0.144", features = ["derive"] }
serde_json = "1.0.85"
lazy_static = "1.4.0"
magic = "0.13.0"
sha256 = "1.0.3"
